// <auto-generated />
using System;
using Atlas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atlas.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427031118_Mig01")]
    partial class Mig01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Atlas.Domain.Entities.AccessPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessPointName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessPointTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("DescPageElement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PageElementId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccessPointTypeId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("MenuId");

                    b.ToTable("SYS_AccessPoint");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AccessPointType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AccessPointTypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AccessPointTypeName")
                        .IsUnique()
                        .HasDatabaseName("IX_SYS_AccessPointTypes_AccessPointTypeName");

                    b.ToTable("AccessPointType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            AccessPointTypeName = "LeftMenu"
                        },
                        new
                        {
                            Id = 1,
                            AccessPointTypeName = "Page"
                        },
                        new
                        {
                            Id = 2,
                            AccessPointTypeName = "Element"
                        });
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationName")
                        .IsUnique()
                        .HasDatabaseName("IX_Applications_ApplicationName");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Asistencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaHoraEntrada")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<Guid?>("PlanSesionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FechaHoraEntrada")
                        .HasDatabaseName("IX_Asistencias_FechaHoraEntrada");

                    b.HasIndex("PlanId");

                    b.HasIndex("PlanSesionId");

                    b.HasIndex("SocioId")
                        .HasDatabaseName("IX_Asistencias_SocioId");

                    b.HasIndex("SocioId", "FechaHoraEntrada")
                        .HasDatabaseName("IX_Asistencias_Socio_FechaEntrada");

                    b.ToTable("Asistencias", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre", "Apellido")
                        .HasDatabaseName("IX_Empleado_NombreApellido");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Membresia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("DiasGracia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("EsLibre")
                        .HasColumnType("bit");

                    b.Property<bool>("EsProgramado")
                        .HasColumnType("bit");

                    b.Property<bool>("EsTicket")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IVASaldo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoSaldo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TicketDisponibles")
                        .HasColumnType("int");

                    b.Property<int>("TicketTotal")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSaldo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("FechaVencimiento")
                        .HasDatabaseName("IX_Membresias_FechaVencimiento");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("IX_Membresias_ProductoId");

                    b.HasIndex("SocioId")
                        .HasDatabaseName("IX_Membresias_SocioId");

                    b.HasIndex("SocioId", "FechaVencimiento")
                        .HasDatabaseName("IX_Membresias_Socio_FechaVencimiento");

                    b.ToTable("Membresias", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.MembresiaPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("IVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MembresiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PagoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FechaPago")
                        .HasDatabaseName("IX_MembresiasPagos_FechaPago");

                    b.HasIndex("MembresiaId")
                        .HasDatabaseName("IX_MembresiasPagos_MembresiaId");

                    b.HasIndex("PagoId")
                        .HasDatabaseName("IX_MembresiasPagos_PagoId");

                    b.HasIndex("MembresiaId", "PagoId")
                        .IsUnique()
                        .HasDatabaseName("UK_MembresiasPagos_MembresiaPago");

                    b.ToTable("MembresiasPagos", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Menus_Name");

                    b.ToTable("Menus", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("MontoPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoPagoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaPago")
                        .HasDatabaseName("IX_Pagos_FechaPago");

                    b.HasIndex("TipoPagoId")
                        .HasDatabaseName("IX_Pagos_TipoPagoId");

                    b.HasIndex("FechaPago", "TipoPagoId")
                        .HasDatabaseName("IX_Pagos_Fecha_TipoPago");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Periodicidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Activa");

                    b.Property<string>("NomPeriodicidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NomPeriodicidad");

                    b.Property<int>("Unidad")
                        .HasColumnType("int")
                        .HasColumnName("Unidad");

                    b.Property<int>("Valor")
                        .HasColumnType("int")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("Activa")
                        .HasDatabaseName("IX_Periodicidades_Activa");

                    b.HasIndex("NomPeriodicidad")
                        .IsUnique()
                        .HasDatabaseName("IX_Periodicidades_NomPeriodicidad");

                    b.ToTable("Periodicidades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            NomPeriodicidad = "Diaria",
                            Unidad = 1,
                            Valor = 1
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            NomPeriodicidad = "Semanal",
                            Unidad = 1,
                            Valor = 7
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            NomPeriodicidad = "Quincenal",
                            Unidad = 1,
                            Valor = 15
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            NomPeriodicidad = "Mensual",
                            Unidad = 2,
                            Valor = 1
                        });
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CupoMaximo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DiasGracia")
                        .HasColumnType("int");

                    b.Property<bool>("EsLibre")
                        .HasColumnType("bit");

                    b.Property<bool>("EsProgramado")
                        .HasColumnType("bit");

                    b.Property<bool>("EsTicket")
                        .HasColumnType("bit");

                    b.Property<string>("NomPlan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PeriodicidadId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_Planes_Activo");

                    b.HasIndex("NomPlan")
                        .IsUnique()
                        .HasDatabaseName("IX_Planes_NomPlan");

                    b.HasIndex("PeriodicidadId")
                        .HasDatabaseName("IX_Planes_PeriodicidadId");

                    b.HasIndex("ServicioId")
                        .HasDatabaseName("IX_Planes_ServicioId");

                    b.HasIndex("Activo", "NomPlan")
                        .HasDatabaseName("IX_Planes_Activo_NomPlan");

                    b.HasIndex("ServicioId", "Activo")
                        .HasDatabaseName("IX_Planes_ServicioId_Activo");

                    b.ToTable("Planes", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.PlanHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId")
                        .HasDatabaseName("IX_PlanHorario_EmpleadoId");

                    b.HasIndex("PlanId", "EmpleadoId", "DiaSemana")
                        .HasDatabaseName("IX_PlanHorario_PlanEmpleadoDia");

                    b.ToTable("PlanesHorario", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlanHorario_HoraFin", "HoraFin > HoraInicio");
                        });
                });

            modelBuilder.Entity("Atlas.Domain.Entities.PlanSesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("PlanHorarioId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId")
                        .HasDatabaseName("IX_PlanSesion_EmpleadoId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_PlanSesion_Estado");

                    b.HasIndex("PlanHorarioId")
                        .HasDatabaseName("IX_PlanSesion_PlanHorarioId");

                    b.HasIndex("PlanId", "Fecha")
                        .HasDatabaseName("IX_PlanSesion_PlanFecha");

                    b.HasIndex("Fecha", "Estado", "PlanId")
                        .HasDatabaseName("IX_PlanSesion_FechaEstadoPlan");

                    b.ToTable("PlanesSesion", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsEnabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NormalizedName");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Name");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_NormalizedName")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.RolAccessPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccessPointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessPointId")
                        .HasDatabaseName("IX_RolAccessPoints_AccessPointId");

                    b.HasIndex("RolId", "AccessPointId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolAccessPoints_RolId_AccessPointId");

                    b.ToTable("RolAccessPoints", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(4);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(3);

                    b.Property<string>("NomServicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_Servicios_Activo");

                    b.HasIndex("NomServicio")
                        .IsUnique()
                        .HasDatabaseName("IX_Servicios_NombreServicio");

                    b.ToTable("Servicios", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ServicioHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int")
                        .HasColumnName("DiaSemana");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("HoraFin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("HoraInicio");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_ServiciosHorarios_Activo");

                    b.HasIndex("EmpleadoId")
                        .HasDatabaseName("IX_ServiciosHorarios_EmpleadoId");

                    b.HasIndex("ServicioId")
                        .HasDatabaseName("IX_ServiciosHorarios_ServicioId");

                    b.HasIndex("EmpleadoId", "DiaSemana", "HoraInicio")
                        .IsUnique()
                        .HasDatabaseName("UK_ServiciosHorarios_Empleado_Dia_HoraInicio");

                    b.HasIndex("ServicioId", "EmpleadoId", "DiaSemana")
                        .HasDatabaseName("IX_ServiciosHorarios_Servicio_Empleado_Dia");

                    b.ToTable("ServicioHorarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_ServiciosHorarios_HoraInicio_Menor_HoraFin", "HoraInicio < HoraFin");
                        });
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Socio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Apellido");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("DNI");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("FechaNacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRegistro")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FotoUrl");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique()
                        .HasDatabaseName("IX_Socios_DNI");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Socios_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Apellido", "Nombre")
                        .HasDatabaseName("IX_Socios_Apellido_Nombre");

                    b.ToTable("Socios", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TipoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NomTipoPago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NomTipoPago");

                    b.HasKey("Id");

                    b.HasIndex("NomTipoPago")
                        .IsUnique()
                        .HasDatabaseName("IX_TiposPago_NomTipoPago");

                    b.ToTable("TiposPago", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("Avatar");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRegistro")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Telefono");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("Telefono")
                        .HasDatabaseName("IX_Usuario_Telefono");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AccessPoint", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.AccessPointType", "SYS_AccessPointType")
                        .WithMany()
                        .HasForeignKey("AccessPointTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.Application", null)
                        .WithMany("AccessPoints")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.Menu", "SYS_Menu")
                        .WithMany("AccessPoint")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SYS_AccessPointType");

                    b.Navigation("SYS_Menu");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Asistencia", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Plan", "Plan")
                        .WithMany("Asistencias")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.PlanSesion", "Sesion")
                        .WithMany("Asistencias")
                        .HasForeignKey("PlanSesionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Atlas.Domain.Entities.Socio", "Socio")
                        .WithMany("Asistencias")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Sesion");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Membresia", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Plan", "Plan")
                        .WithMany("Membresias")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.MembresiaPago", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Membresia", "Membresia")
                        .WithMany("MembresiaPagos")
                        .HasForeignKey("MembresiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.Pago", "Pago")
                        .WithMany("MembresiaPagos")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membresia");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Pago", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.TipoPago", "TipoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("TipoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoPago");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Plan", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Periodicidad", "Periodicidad")
                        .WithMany("Planes")
                        .HasForeignKey("PeriodicidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.Servicio", "Servicio")
                        .WithMany("Planes")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Periodicidad");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.PlanHorario", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Empleado", "Empleado")
                        .WithMany("PlanHorarios")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.Plan", "Plan")
                        .WithMany("Horarios")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.PlanSesion", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.PlanHorario", "Horario")
                        .WithMany()
                        .HasForeignKey("PlanHorarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.Plan", "Plan")
                        .WithMany("Sesiones")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Horario");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.RolAccessPoint", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.AccessPoint", "AccessPoint")
                        .WithMany("SYS_RolAccessPoint")
                        .HasForeignKey("AccessPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccessPoint");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ServicioHorario", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Empleado", "Empleado")
                        .WithMany("ServicioHorarios")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.Servicio", "Servicio")
                        .WithMany("Horarios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AccessPoint", b =>
                {
                    b.Navigation("SYS_RolAccessPoint");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Application", b =>
                {
                    b.Navigation("AccessPoints");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("PlanHorarios");

                    b.Navigation("ServicioHorarios");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Membresia", b =>
                {
                    b.Navigation("MembresiaPagos");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Menu", b =>
                {
                    b.Navigation("AccessPoint");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Pago", b =>
                {
                    b.Navigation("MembresiaPagos");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Periodicidad", b =>
                {
                    b.Navigation("Planes");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Horarios");

                    b.Navigation("Membresias");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.PlanSesion", b =>
                {
                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Planes");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Socio", b =>
                {
                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TipoPago", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
